/**
 * POST /api/bots/pair
 * Links a bot (identified by a short pairing code) to a human wallet.
 * The code is generated by `npx djinn-skill` and stored in Supabase for 10 minutes.
 *
 * Security:
 * - Code must exist, be unused, and not expired
 * - Human wallet must already have a claimed profile (username)
 * - Response does not leak cap numbers
 */
import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

export async function POST(request: Request) {
    try {
        const { code, walletAddress } = await request.json();

        if (!code || !walletAddress) {
            return NextResponse.json({ error: 'code and walletAddress are required' }, { status: 400 });
        }

        const supabase = createClient(
            process.env.NEXT_PUBLIC_SUPABASE_URL!,
            process.env.SUPABASE_SERVICE_ROLE_KEY!
        );

        // ─── Verify human has a claimed profile ──────────────────────────────
        const { data: humanProfile } = await supabase
            .from('profiles')
            .select('id, username')
            .eq('wallet_address', walletAddress)
            .single();

        if (!humanProfile || !humanProfile.username) {
            return NextResponse.json(
                { error: 'You must claim a username first before linking a bot.' },
                { status: 403 }
            );
        }

        // ─── Look up the pairing code ────────────────────────────────────────
        const { data: pair, error } = await supabase
            .from('bot_pair_codes')
            .select('*')
            .eq('code', code.toUpperCase())
            .eq('used', false)
            .gt('expires_at', new Date().toISOString())
            .single();

        if (error || !pair) {
            return NextResponse.json({ error: 'Invalid or expired code. Run npx djinn-skill again.' }, { status: 404 });
        }

        // ─── Link the bot wallet to the human wallet ─────────────────────────
        await supabase
            .from('profiles')
            .update({ linked_human_wallet: walletAddress })
            .eq('wallet_address', pair.bot_wallet);

        // ─── Mark code as used ───────────────────────────────────────────────
        await supabase
            .from('bot_pair_codes')
            .update({ used: true, linked_at: new Date().toISOString(), linked_human_wallet: walletAddress })
            .eq('code', code.toUpperCase());

        // ─── Get bot info ────────────────────────────────────────────────────
        const { data: botProfile } = await supabase
            .from('profiles')
            .select('username, created_at')
            .eq('wallet_address', pair.bot_wallet)
            .single();

        // Bot position = count of clawbots registered at or before this one
        const { count: botPosition } = await supabase
            .from('profiles')
            .select('id', { count: 'exact', head: true })
            .eq('agent_type', 'clawbot')
            .lte('created_at', botProfile?.created_at ?? new Date().toISOString());

        // Extract private key if present
        let privateKey = '';
        if (pair.bot_name && pair.bot_name.includes('|||')) {
            privateKey = pair.bot_name.split('|||')[1];
        }

        return NextResponse.json({
            success: true,
            botName: botProfile?.username || 'ClawBot',
            position: botPosition ?? 1,
            privateKey,
        });

    } catch (e: any) {
        console.error('[BOT-PAIR]', e);
        return NextResponse.json({ error: 'Pairing failed' }, { status: 500 });
    }
}
