#!/usr/bin/env node

/**
 * @djinn/setup — Quick setup CLI for Djinn AI bot developers
 *
 * Usage:
 *   npx @djinn/setup
 *
 * What it does:
 *   1. Validates activation code
 *   2. Generates a Solana keypair for the bot
 *   3. Creates .env config with Djinn settings
 *   4. Claims the code with bot data
 *   5. Prints Magic Link to complete registration
 */

import * as fs from 'fs';
import * as path from 'path';
import { createHash } from 'crypto';
import { execSync } from 'child_process';
import prompts from 'prompts';
import {
    Keypair, Connection, LAMPORTS_PER_SOL, PublicKey,
    TransactionInstruction, TransactionMessage, VersionedTransaction,
    SystemProgram,
} from '@solana/web3.js';
import bs58 from 'bs58';

const DJINN_BANNER = `
╔══════════════════════════════════════════════════════════════╗
║                                                              ║
║     ██████╗      ██╗██╗███╗   ██╗███╗   ██╗                ║
║     ██╔══██╗     ██║██║████╗  ██║████╗  ██║                ║
║     ██║  ██║     ██║██║██╔██╗ ██║██╔██╗ ██║                ║
║     ██║  ██║██   ██║██║██║╚██╗██║██║╚██╗██║                ║
║     ██████╔╝╚█████╔╝██║██║ ╚████║██║ ╚████║                ║
║     ╚═════╝  ╚════╝ ╚═╝╚═╝  ╚═══╝╚═╝  ╚═══╝                ║
║                                                              ║
║              AI Bot Setup Wizard v2.0.0                      ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
`;

const CATEGORIES = ['All', 'Sports', 'Crypto', 'Politics', 'Other'];
const DJINN_PROGRAM_ID = 'A8pVMgP6vwjGqcbYh1WGWDjXq9uwQRoF9Lz1siLmD7nm';

async function main() {
    console.log(DJINN_BANNER);
    console.log('  Welcome to Djinn! Let\'s set up your AI trading bot.\n');

    // ─── Arg Parsing (Non-Interactive Mode) ─────────────────────────────────
    const args = process.argv.slice(2);
    const overrides: any = {};
    args.forEach(arg => {
        if (arg.startsWith('--')) {
            const [key, val] = arg.slice(2).split('=');
            if (!key) return;
            if (key === 'name' || key === 'botName') overrides.botName = val;
            if (key === 'code') overrides.activationCode = val;
            if (key === 'rpc' || key === 'rpcUrl') overrides.rpcUrl = val;
            if (key === 'webhook' || key === 'webhookUrl') overrides.webhookUrl = val;
            if (key === 'network') overrides.network = val;
            if (key === 'category') {
                const idx = CATEGORIES.findIndex(c => c.toLowerCase() === (val || '').toLowerCase());
                if (idx >= 0) overrides.category = idx;
            }
            if (key === 'force' || key === 'overwrite') overrides.overwrite = true;
        }
    });
    prompts.override(overrides);

    // ─── Global Config ──────────────────────────────────────────────────────
    let network = overrides.network || 'devnet';

    if (Object.keys(overrides).length > 0) {
        console.log('  ⚡ Auto-Pilot Mode engaged.');
        if (overrides.activationCode) console.log(`  🔹 Code: \x1b[36m${overrides.activationCode}\x1b[0m`);
        if (overrides.botName) console.log(`  🔹 Bot Name: \x1b[36m${overrides.botName}\x1b[0m`);
        if (overrides.category !== undefined) console.log(`  🔹 Category: \x1b[36m${CATEGORIES[overrides.category]}\x1b[0m`);
        // network already logged below if set
    }
    if (overrides.network) console.log(`  🔹 Network: \x1b[36m${overrides.network}\x1b[0m`);
    if (Object.keys(overrides).length > 0) console.log('');

    // ─── Step 0: Activation Code ───────────────────────────────────────────
    console.log('🔑 Step 0: Activation Code\n');
    console.log('  Activation codes are generated by the Djinn team.');
    console.log('  Visit https://djinn.world/bots or contact the team to get yours.\n');

    let code = overrides.activationCode || '';

    if (!code) {
        const { activationCode } = await prompts({
            type: 'text',
            name: 'activationCode',
            message: 'Enter your Djinn activation code (format: DJNN-XXXX):',
            validate: (v: string) => v.trim().length > 0 ? true : 'Activation code is required',
        }, {
            onCancel: () => {
                console.log('\n❌ Setup cancelled.');
                process.exit(0);
            }
        });
        code = (activationCode as string).trim().toUpperCase();
    }

    console.log(`  Code: \x1b[36m${code}\x1b[0m\n`);

    // Determine API URL (devnet = localhost, mainnet = production)
    // We'll ask network first for this, but default to devnet for validation
    const apiUrl = overrides.network === 'mainnet' ? 'https://djinn.world' : 'http://localhost:3000';

    // Validate code against API
    console.log('\n  🔍 Validating code...');
    try {
        const verifyRes = await fetch(`${apiUrl}/api/bot/codes/verify?code=${encodeURIComponent(code)}`);
        const verifyData = await verifyRes.json();

        if (!verifyData.valid) {
            console.error(`\n  ❌ Invalid code: ${verifyData.reason || 'Unknown error'}`);
            console.error('  Get a valid code from the Djinn team.\n');
            process.exit(1);
        }

        if (verifyData.status === 'claimed') {
            console.error(`\n  ❌ This code has already been claimed.`);
            console.error('  If this is yours, use the Magic Link from your previous setup.\n');
            process.exit(1);
        }

        console.log('  ✅ Code is valid!\n');
    } catch (e) {
        console.error('\n  ⚠️  Could not validate code (API not reachable).');
        console.error('  Make sure the Djinn app is running: yarn dev\n');
        console.error('  Continuing anyway...\n');
    }

    // ─── Step 1: Prerequisites ──────────────────────────────────────────────
    const nodeVersion = parseInt(process.version.slice(1).split('.')[0]);
    if (nodeVersion < 22) {
        console.warn(`⚠️  Warning: OpenClaw recommends Node.js 22+. You have v${process.version}.`);
    }

    console.log('🔍 Checking OpenClaw Engine...');
    try {
        execSync('which openclaw', { stdio: 'ignore' });
        console.log('✅ OpenClaw is installed.');
    } catch (e) {
        console.error('❌ OpenClaw (clawd) not found.');
        console.error('   Please install it manually from: https://openclaw.ai');
        console.error('   Then run this setup again.');
        process.exit(1);
    }

    // ─── Step 2: Bot Configuration ──────────────────────────────────────────
    console.log('\n📋 Step 2: Network Configuration\n');

    const response = await prompts([
        {
            type: 'select',
            name: 'network',
            message: 'Select Network:',
            choices: [
                { title: 'Devnet (Testing)', value: 'devnet' },
                { title: 'Mainnet (Real Money)', value: 'mainnet' }
            ],
            initial: 0
        },
        {
            type: 'text',
            name: 'rpcUrl',
            message: 'RPC URL (Leave empty for default):',
        },
        {
            type: 'text',
            name: 'webhookUrl',
            message: 'Webhook URL (Optional):',
        }
    ], {
        onCancel: () => {
            console.log('\n❌ Setup cancelled.');
            process.exit(0);
        }
    });

    if (response.network) network = response.network;

    // ─── Step 2b: Bot Identity ──────────────────────────────────────────
    console.log('\n🤖 Step 2b: Bot Identity\n');

    const identityResponse = await prompts([
        {
            type: 'text',
            name: 'botName',
            message: 'Bot Name (max 32 chars):',
            initial: overrides.botName || '',
            validate: (v: string) => v.length > 0 && v.length <= 32 ? true : 'Name must be 1-32 characters',
        },
        {
            type: 'select',
            name: 'category',
            message: 'Strategy Category:',
            choices: CATEGORIES.map((c, i) => ({ title: `${c}`, value: i })),
            initial: overrides.category || 0,
        },
    ], {
        onCancel: () => {
            console.log('\n❌ Setup cancelled.');
            process.exit(0);
        }
    });

    const botName = identityResponse.botName || 'Djinn Bot';
    const category = identityResponse.category ?? 0;
    const defaultRpc = network === 'devnet' ? 'https://api.devnet.solana.com' : 'https://api.mainnet-beta.solana.com';
    const rpcUrl = response.rpcUrl || defaultRpc;
    const webhookUrl = response.webhookUrl;

    // ─── Step 3: Generate Wallet ──────────────────────────────────────────
    console.log('\n🔑 Step 3: Generating Bot Wallet\n');

    const djinnDir = path.join(process.env.HOME || '.', '.djinn');
    if (!fs.existsSync(djinnDir)) {
        fs.mkdirSync(djinnDir, { recursive: true });
    }

    const walletPath = path.join(djinnDir, 'bot-wallet.json');

    if (fs.existsSync(walletPath)) {
        console.log(`  ⚠️  Wallet already exists at ${walletPath}`);
        const { overwrite } = await prompts({
            type: 'confirm',
            name: 'overwrite',
            message: 'Overwrite existing wallet?',
            initial: false
        });

        if (!overwrite) {
            console.log('  Using existing wallet.');
        } else {
            generateWallet(walletPath);
        }
    } else {
        generateWallet(walletPath);
    }

    // Read wallet public key for claiming
    const fileContent = fs.readFileSync(walletPath, 'utf-8');
    const secretKey = new Uint8Array(JSON.parse(fileContent));
    const kp = Keypair.fromSecretKey(secretKey);
    const botWalletPubkey = kp.publicKey.toBase58();

    // ─── Step 3.5: Auto-Fund (Devnet) ──────────────────────────────────
    const connection = new Connection(rpcUrl, 'confirmed');

    if (network === 'devnet') {
        console.log('\n💸 Auto-Funding Wallet (Devnet)\n');

        try {
            let balance = await connection.getBalance(kp.publicKey);
            const REQUIRED_SOL = 11; // 10 SOL stake + fees

            if (balance < REQUIRED_SOL * LAMPORTS_PER_SOL) {
                // Request multiple airdrops (devnet limits ~2 SOL per request)
                const rounds = Math.ceil((REQUIRED_SOL * LAMPORTS_PER_SOL - balance) / (2 * LAMPORTS_PER_SOL));
                for (let i = 0; i < Math.min(rounds, 6); i++) {
                    try {
                        console.log(`  💧 Airdrop ${i + 1}/${rounds}...`);
                        const sig = await connection.requestAirdrop(kp.publicKey, 2 * LAMPORTS_PER_SOL);
                        await connection.confirmTransaction(sig);
                        await new Promise(r => setTimeout(r, 1000)); // Rate limit pause
                    } catch {
                        console.log(`  ⚠️  Airdrop ${i + 1} failed (rate limited). Continuing...`);
                        break;
                    }
                }
                balance = await connection.getBalance(kp.publicKey);
                console.log(`  ✅ Balance: ${balance / LAMPORTS_PER_SOL} SOL`);
                if (balance < 10 * LAMPORTS_PER_SOL) {
                    console.log(`  ⚠️  Need 10+ SOL for registration. Use faucet: https://faucet.solana.com`);
                    console.log(`  Wallet: ${botWalletPubkey}`);
                }
            } else {
                console.log(`  ✅ Wallet already funded: ${balance / LAMPORTS_PER_SOL} SOL`);
            }
        } catch (e) {
            console.log('  ⚠️  Airdrop failed. You may need to use a faucet: https://faucet.solana.com');
        }
    }

    // ─── Step 3.6: Register Bot On-Chain ──────────────────────────────
    console.log('\n⛓️  Step 3.6: Registering Bot On-Chain\n');

    let registeredOnChain = false;
    const programId = new PublicKey(DJINN_PROGRAM_ID);

    try {
        const balance = await connection.getBalance(kp.publicKey);
        if (balance < 10 * LAMPORTS_PER_SOL) {
            console.log(`  ⚠️  Insufficient balance (${balance / LAMPORTS_PER_SOL} SOL). Need 10+ SOL.`);
            console.log('  Skipping on-chain registration. You can register later via the web.\n');
        } else {
            // Derive PDAs
            const [botProfilePDA] = PublicKey.findProgramAddressSync(
                [Buffer.from('bot_profile'), kp.publicKey.toBuffer()],
                programId
            );
            const [botEscrowPDA] = PublicKey.findProgramAddressSync(
                [Buffer.from('bot_escrow'), kp.publicKey.toBuffer()],
                programId
            );

            // Check if already registered
            const existingAccount = await connection.getAccountInfo(botProfilePDA);
            if (existingAccount) {
                console.log('  ✅ Bot already registered on-chain!');
                console.log(`  PDA: ${botProfilePDA.toBase58()}`);
                registeredOnChain = true;
            } else {
                // Build registerBot instruction manually (no Anchor dependency)
                const discriminator = createHash('sha256')
                    .update('global:register_bot')
                    .digest()
                    .slice(0, 8);

                const nameBytes = Buffer.from(botName, 'utf-8');
                const metadataUri = JSON.stringify({
                    description: `Autonomous ${CATEGORIES[category] || 'general'} prediction agent`,
                    image: `https://api.dicebear.com/9.x/bottts-neutral/svg?seed=${botName}`,
                });
                const uriBytes = Buffer.from(metadataUri, 'utf-8');

                // Borsh serialization: discriminator + string(name) + string(uri) + u8(category)
                const data = Buffer.alloc(8 + 4 + nameBytes.length + 4 + uriBytes.length + 1);
                let offset = 0;
                discriminator.copy(data, offset); offset += 8;
                data.writeUInt32LE(nameBytes.length, offset); offset += 4;
                nameBytes.copy(data, offset); offset += nameBytes.length;
                data.writeUInt32LE(uriBytes.length, offset); offset += 4;
                uriBytes.copy(data, offset); offset += uriBytes.length;
                data.writeUInt8(category, offset);

                const instruction = new TransactionInstruction({
                    keys: [
                        { pubkey: botProfilePDA, isSigner: false, isWritable: true },
                        { pubkey: botEscrowPDA, isSigner: false, isWritable: true },
                        { pubkey: kp.publicKey, isSigner: true, isWritable: true },
                        { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
                    ],
                    programId,
                    data,
                });

                console.log('  📡 Sending registerBot transaction...');
                const { blockhash } = await connection.getLatestBlockhash();
                const messageV0 = new TransactionMessage({
                    payerKey: kp.publicKey,
                    recentBlockhash: blockhash,
                    instructions: [instruction],
                }).compileToV0Message();

                const tx = new VersionedTransaction(messageV0);
                tx.sign([kp]);

                const txSig = await connection.sendTransaction(tx);
                console.log(`  ⏳ Confirming tx: ${txSig}`);
                await connection.confirmTransaction(txSig);

                console.log(`  ✅ Bot registered on-chain!`);
                console.log(`  PDA: ${botProfilePDA.toBase58()}`);
                console.log(`  TX: ${txSig}`);
                registeredOnChain = true;
            }
        }
    } catch (e: unknown) {
        const err = e as Error;
        let msg = err.message || 'Unknown error';
        if (msg.includes('custom program error: 0x0')) msg = 'Bot already registered or name taken';
        console.log(`  ⚠️  On-chain registration failed: ${msg}`);
        console.log('  You can register later via the Magic Link.\n');
    }

    // ─── Step 3.7: Mark Code as Used sent to API ────────────────────────
    if (registeredOnChain) {
        try {
            const finalApiUrl = network === 'devnet' ? 'http://localhost:3000' : 'https://djinn.world';
            const [botProfilePDA] = PublicKey.findProgramAddressSync(
                [Buffer.from('bot_profile'), kp.publicKey.toBuffer()],
                programId
            );

            await fetch(`${finalApiUrl}/api/bot/codes/use`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    code,
                    ownerWallet: kp.publicKey.toBase58(),
                    botProfilePda: botProfilePDA.toBase58(),
                }),
            });
            console.log('  ✅ Activation Code marked as USED.');
        } catch (e) {
            console.log('  ⚠️  Failed to update code status (API unreachable).');
        }
    }

    // ─── Step 4: Claim Activation Code ──────────────────────────────────
    console.log('\n📡 Step 4: Claiming Activation Code\n');

    const finalApiUrl = network === 'devnet' ? 'http://localhost:3000' : 'https://djinn.world';

    try {
        const claimRes = await fetch(`${finalApiUrl}/api/bot/codes/claim`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                code,
                botName,
                category,
                botWallet: botWalletPubkey,
            }),
        });

        const claimData = await claimRes.json();

        if (claimData.success) {
            console.log('  ✅ Code claimed successfully!');
        } else {
            console.log(`  ⚠️  Could not claim code: ${claimData.error || 'Unknown'}`);
        }

        // If bot was registered on-chain, also mark code as "used"
        if (registeredOnChain) {
            try {
                const [botProfilePDA] = PublicKey.findProgramAddressSync(
                    [Buffer.from('bot_profile'), kp.publicKey.toBuffer()],
                    programId
                );
                await fetch(`${finalApiUrl}/api/bot/codes/use`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({
                        code,
                        ownerWallet: botWalletPubkey,
                        botProfilePda: botProfilePDA.toBase58(),
                    }),
                });
                console.log('  ✅ Code marked as used!');
            } catch {
                // Non-critical
            }
        }
    } catch (e) {
        console.log('  ⚠️  Could not reach API to claim code. Continue manually.');
    }

    // ─── Step 5: Write .env ──────────────────────────────────────────────
    console.log('\n📝 Step 5: Writing Configuration\n');

    const envContent = `# Djinn AI Bot Configuration
# Generated by @djinn/setup

DJINN_ACTIVATION_CODE=${code}
DJINN_RPC_URL=${rpcUrl}
DJINN_BOT_KEYPAIR_PATH=${walletPath}
DJINN_API_URL=${finalApiUrl}
DJINN_PROGRAM_ID=${DJINN_PROGRAM_ID}
DJINN_BOT_NAME=${botName}
DJINN_STRATEGY_CATEGORY=${category}
DJINN_NETWORK=${network}
${webhookUrl ? `DJINN_WEBHOOK_URL=${webhookUrl}` : '# DJINN_WEBHOOK_URL=https://your-bot.example.com/djinn'}
`;

    const envPath = path.join(djinnDir, '.env.djinn');
    fs.writeFileSync(envPath, envContent);
    console.log(`  ✅ Config written to ${envPath}`);

    // ─── Step 6: Install SDK ──────────────────────────────────────────────
    console.log('\n📦 Step 6: Installing @djinn/sdk\n');

    try {
        execSync('npm install @djinn/sdk', { stdio: 'inherit' });
        console.log('  ✅ SDK installed');
    } catch {
        console.log('  ⚠️  SDK not yet published. You can install it later.');
    }

    // ─── Step 7: Install Agent Skill ──────────────────────────────────────
    console.log('\n🧠 Step 7: Installing @djinn/agent-skill (The Brain)\n');

    try {
        execSync('npm install @djinn/agent-skill', { stdio: 'inherit' });
        console.log('  ✅ Agent Skill installed');
    } catch {
        console.log('  ⚠️  Skill package not found (Run locally if testing).');
    }

    // ─── Done ──────────────────────────────────────────────────────────────
    console.log('\n' + '═'.repeat(60));
    console.log('\n🎉 Setup complete!\n');

    if (registeredOnChain) {
        console.log('  ✅ BOT STATUS: REGISTERED ON-CHAIN');
        console.log('  ┌──────────────────────────────────────────────────────┐');
        console.log(`  │  🤖 ${botName}`);
        console.log(`  │  📍 Wallet: ${botWalletPubkey}`);
        console.log(`  │  🏷️  Category: ${CATEGORIES[category] || 'All'}`);
        console.log(`  │  💰 Stake: 10 SOL (in escrow)`);
        console.log('  │  🔑 The bot signs its own transactions autonomously │');
        console.log('  └──────────────────────────────────────────────────────┘\n');

        console.log('  NEXT STEPS:\n');
        console.log('  1. View your bot on the dashboard:');
        const baseUrl = network === 'devnet' ? 'http://localhost:3000' : 'https://djinn.world';
        console.log(`\n     👉 \x1b[36m${baseUrl}/bots\x1b[0m\n`);
        console.log('  2. Start your bot (OpenClaw or custom logic):');
        console.log('     // Your bot reads .env.djinn and trades autonomously');
        console.log('     const markets = await djinn.listMarkets();\n');
    } else {
        console.log('  ⚠️  BOT STATUS: NOT YET REGISTERED ON-CHAIN');
        console.log('  ┌──────────────────────────────────────────────────────┐');
        console.log(`  │  🤖 Bot Wallet: ${botWalletPubkey}`);
        console.log('  │  💰 Need 10+ SOL to register                        │');
        console.log('  └──────────────────────────────────────────────────────┘\n');

        console.log('  NEXT STEPS:\n');
        if (network === 'devnet') {
            console.log('  1. Fund bot wallet via faucet: https://faucet.solana.com');
            console.log(`     Wallet: ${botWalletPubkey}\n`);
            console.log('  2. Re-run setup: npx @djinn/setup\n');
        } else {
            console.log('  1. Send 11+ SOL to bot wallet:');
            console.log(`     ${botWalletPubkey}\n`);
            console.log('  2. Complete registration on the web:');
            const baseUrl = 'https://djinn.world';
            const magicLink = `${baseUrl}/bots?code=${encodeURIComponent(code)}`;
            console.log(`\n     👉 \x1b[36m${magicLink}\x1b[0m\n`);
        }
    }

    console.log('  📖 Full docs: https://docs.djinn.world/bots');
    console.log('  💬 Discord: https://discord.gg/djinn\n');
}

function generateWallet(walletPath: string) {
    const kp = Keypair.generate();
    const secretKey = Array.from(kp.secretKey);
    fs.writeFileSync(walletPath, JSON.stringify(secretKey));
    fs.chmodSync(walletPath, 0o600); // Owner read/write only
    console.log(`  ✅ New wallet generated: ${walletPath}`);
    console.log(`  📍 Public Key: ${kp.publicKey.toBase58()}`);
    const bs58Key = bs58.encode(kp.secretKey);
    console.log(`  🔐 Private Key (BS58):`);
    console.log(`\n${bs58Key}\n`);

    // Try to copy to clipboard on Mac
    if (process.platform === 'darwin') {
        try {
            execSync(`echo "${bs58Key}" | pbcopy`);
            console.log('  📋 (Copied to clipboard!)');
        } catch (e) {
            // Ignore if pbcopy fails
        }
    }

    console.log('  ⚠️  BACK UP THIS KEY! If lost, your stake is gone.');
}

main().catch(console.error);
